
package com.wiiy.core.newsWebService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WebInfoServiceImplService", targetNamespace = "http://impl.service.webService.cloudService.wiiy.com/", wsdlLocation = "http://211.152.54.193:96/cloudService/webInfoService?wsdl")
public class WebInfoServiceImplService
    extends Service
{

    private final static URL WEBINFOSERVICEIMPLSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://211.152.54.193:96/cloudService/webInfoService?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WEBINFOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public WebInfoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebInfoServiceImplService() {
        super(WEBINFOSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://impl.service.webService.cloudService.wiiy.com/", "WebInfoServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns WebInfoService
     */
    @WebEndpoint(name = "WebInfoServiceImplPort")
    public WebInfoService getWebInfoServiceImplPort() {
        return (WebInfoService)super.getPort(new QName("http://impl.service.webService.cloudService.wiiy.com/", "WebInfoServiceImplPort"), WebInfoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebInfoService
     */
    @WebEndpoint(name = "WebInfoServiceImplPort")
    public WebInfoService getWebInfoServiceImplPort(WebServiceFeature... features) {
        return (WebInfoService)super.getPort(new QName("http://impl.service.webService.cloudService.wiiy.com/", "WebInfoServiceImplPort"), WebInfoService.class, features);
    }

}
