
package com.wiiy.core.newsWebService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "webInfoService", targetNamespace = "http://service.webService.cloudService.wiiy.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WebInfoService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "webInfoList", targetNamespace = "")
    @RequestWrapper(localName = "getWebInfoList", targetNamespace = "http://service.webService.cloudService.wiiy.com/", className = "com.wiiy.cloudservice.webservice.service.GetWebInfoList")
    @ResponseWrapper(localName = "getWebInfoListResponse", targetNamespace = "http://service.webService.cloudService.wiiy.com/", className = "com.wiiy.cloudservice.webservice.service.GetWebInfoListResponse")
    public String getWebInfoList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
